// <auto-generated />
namespace MVC_IA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MemberRequiredNot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberRequiredNot));
        
        string IMigrationMetadata.Id
        {
            get { return "202003120741323_MemberRequiredNot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
