// <auto-generated />
namespace MVC_IA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class passwordsalt_Time : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passwordsalt_Time));
        
        string IMigrationMetadata.Id
        {
            get { return "202002170505551_passwordsalt_Time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
